name: notesapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.5

dev_dependencies:
  cloud_firestore: ^4.4.3
  firebase_core: ^2.7.0
  flutter_lints: ^2.0.0
  flutter_speed_dial: ^6.2.0
  flutter_test:
    sdk: flutter
  get: ^4.6.5
  get_cli: ^1.8.1
  intl: ^0.18.0

flutter:
  assets:
    - assets/
  uses-material-design: true
